[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/mandulaj/PZEM-004T-v30
    knolleary/PubSubClient@^2.8
    https://github.com/tzapu/WiFiManager.git

[env:sensor_node_1]
board = esp32dev
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_flags = 
    -D NODE_ID=1

[env:sensor_node_2]
board = nodemcu-32s
; upload_port = /dev/ttyUSB1
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_flags = 
    -D NODE_ID=2